app/NetFlowInsight/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, send_from_directory
from flask_login import login_required, current_user
from sqlalchemy.orm import joinedload
from werkzeug.utils import secure_filename
from .models import User, Notes, PcapLoc, FileAnalysis, FileResult
from . import db
import os, json, time
from .file_operations.file_analysis import run_analysis
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import logging
from flask_wtf.csrf import validate_csrf
from bleach import clean  # Import bleach for sanitization

# Creating a Blueprint named 'views'
views = Blueprint('views', __name__)

# Flask-Limiter for rate limiting
limiter = Limiter(get_remote_address, app=None)

# Allowed file extensions for uploads
ALLOWED_EXTENSIONS = {'pcap'}

# Configure logging
logging.basicConfig(filename='app.log', level=logging.INFO)

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# Route for the home page
@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)

# Route for file upload
@views.route('/upload', methods=['POST'])
@login_required
@limiter.limit("10 per minute")  # Rate limiting to prevent abuse
def upload():
    start_time = time.time()

    file = request.files['pcap_file']

    # Validate file type
    if not file or not allowed_file(file.filename):
        flash('Please include a valid .pcap file', category='error')
        return redirect(url_for('views.home'))

    # Store the file in the user's directory
    user_directory = current_user.path
    api_key = current_user.api_key
    filename = secure_filename(file.filename)

    pcap_directory = os.path.join(str(user_directory), filename)
    if not os.path.exists(pcap_directory):
        os.makedirs(pcap_directory)
    file_path = os.path.join(str(pcap_directory), filename)

    try:
        # Save the file and store details in the database
        file.save(file_path)
        new_file = PcapLoc(path=file_path, filename=filename, user_id=current_user.id)
        db.session.add(new_file)
        db.session.commit()

        pcap_loc_id = new_file.id

        # File Analysis
        file_analysis_path, file_paths, mime_types, file_results, filenames, extension_types = run_analysis(
            file_path, str(pcap_directory), api_key
        )
        if not file_analysis_path:
            file_analysis = FileAnalysis(path="No Files Detected in the Pcap File!", pcap_loc_id=pcap_loc_id)
            db.session.add(file_analysis)
            db.session.commit()
        else:
            file_analysis = FileAnalysis(path=str(file_analysis_path), pcap_loc_id=pcap_loc_id)
            db.session.add(file_analysis)
            db.session.commit()
            file_analysis_id = file_analysis.id
            for file_path,mime_type,file_result,file_name,extension_type in zip(file_paths, mime_types, file_results, filenames, extension_types):
                file_result_new = FileResult(filepath = str(file_path), mime_type=mime_type, result=file_result, filename=file_name, extension_type=extension_type, file_analysis_id = file_analysis_id)
                db.session.add(file_result_new)
            db.session.commit()

        flash(f'File uploaded successfully!', category='success')

        # Log the upload
        logging.info(f"File uploaded by user {current_user.id}: {file_path}")

        # Calculate and log analysis time
        analysis_time = round(time.time() - start_time, 1)
        logging.info(f"File analysis completed in {analysis_time} seconds")
    except Exception as e:
        flash(f'{e}', category='error')
        logging.error(f"Error during file upload: {e}")

    return redirect(url_for('views.home', user=current_user))

# Route for file analysis results
@views.route('file_analysis_results/', methods=['GET', 'POST'])
@login_required
def file_analysis_results():
    if request.method == 'POST':
        try:
            csrf_token = request.headers.get('X-CSRFToken')
            validate_csrf(csrf_token)
        except Exception as e: 
            return jsonify({"error": "Invalid CSRF token"}), 400

    user = User.query.options(
        joinedload(User.pcap_loc)
        .joinedload(PcapLoc.file_analysis)
        .joinedload(FileAnalysis.file_result),
        joinedload(User.pcap_loc)
    ).filter_by(id=current_user.id).first()

    return render_template("file_analysis_results.html", user=user)

# Route for downloading carved files
@views.route('/download/<path:file_path>')
@login_required
def download_file(file_path):
    user_directory = os.path.abspath(current_user.path)  # Get absolute path of the user's directory

    # Normalize and validate the file path
    file_path = os.path.normpath(file_path)
    real_path = os.path.realpath(file_path)

    # Debugging: Log the paths for troubleshooting
    logging.info(f"User Directory: {user_directory}")
    logging.info(f"Requested File Path: {file_path}")
    logging.info(f"Resolved Real Path: {real_path}")

    # Check if the file path is valid and within the user's directory
    if not real_path.startswith(user_directory) or not os.path.exists(real_path):
        flash('Access denied: Invalid file path or file does not exist.', category='error')
        logging.warning(f"Unauthorized file download attempt by user {current_user.id}: {file_path}")
        return redirect(url_for('views.home'))

    # Extract the directory and filename
    directory = os.path.dirname(real_path)
    filename = os.path.basename(real_path)

    # Sanitize the filename
    from werkzeug.utils import secure_filename
    filename = secure_filename(filename)

    # Serve the file for download
    return send_from_directory(directory=directory, path=filename, as_attachment=True)

# Route for updating the API key
@views.route('/update_api_key', methods=['POST'])
@login_required
@limiter.limit("5 per minute")
def update_api_key():
    try:
        # Validate CSRF token
        csrf_token = request.headers.get('X-CSRFToken')
        validate_csrf(csrf_token)

        # Get the new API key from the request
        new_api_key = request.json.get('api_key')
        if not new_api_key:
            return jsonify({"error": "API key cannot be empty"}), 400

        # Update the user's API key
        user = User.query.get(current_user.id)
        if user:
            user.api_key = new_api_key
            db.session.commit()
            return jsonify({"success": True})
        else:
            return jsonify({"error": "User not found"}), 404
    except Exception as e:
        return jsonify({"error": str(e)}), 400
# Route for updating notes
@views.route('/update_notes', methods=['POST'])
@login_required
def update_notes():
    try:
        # Validate CSRF token
        csrf_token = request.headers.get('X-CSRFToken')
        validate_csrf(csrf_token)

        new_note = clean(request.json.get('note'))  # Sanitize input
        note_id = int(request.json.get('note_id'))
        note = Notes.query.get(note_id)

        if not note:
            raise ValueError('Note not found!')

        # Validate ownership through PcapLoc
        pcap_loc = PcapLoc.query.get(note.pcap_loc_id)
        if not pcap_loc or pcap_loc.user_id != current_user.id:
            raise ValueError('Unauthorized access to note!')

        # Update the note
        note.note = new_note
        db.session.commit()
        logging.info(f"Note {note_id} updated by user {current_user.id}")
    except Exception as e:
        flash(f'{e}', category='error')
        logging.error(f"Error updating note {note_id} for user {current_user.id}: {e}")
        return jsonify({"error": "Invalid CSRF token"}), 400

    return jsonify({"success": True})

# Updated delete_note route
@views.route('delete_note/', methods=['POST'])
@login_required
@limiter.limit("5 per minute")
def delete_note():
    try:
        # Validate CSRF token
        csrf_token = request.headers.get('X-CSRFToken')
        validate_csrf(csrf_token)

        note = json.loads(request.data)
        note_id = int(note.get('note_id'))
        note = Notes.query.get(note_id)

        if not note:
            logging.warning(f"Note {note_id} not found for user {current_user.id}")
            return jsonify({"error": "Note not found"}), 404

        # Validate ownership through PcapLoc
        pcap_loc = PcapLoc.query.get(note.pcap_loc_id)
        if not pcap_loc or pcap_loc.user_id != current_user.id:
            logging.warning(f"Unauthorized delete attempt by user {current_user.id} for note {note_id}")
            return jsonify({"error": "Unauthorized or note not found"}), 403

        # Delete the note
        db.session.delete(note)
        db.session.commit()
        logging.info(f"Note {note_id} deleted by user {current_user.id}")
        return jsonify({"success": True})
    except (ValueError, KeyError) as e:
        logging.error(f"Invalid input for delete_note by user {current_user.id}: {e}")
        return jsonify({"error": "Invalid input"}), 400
    

# Route for viewing and creating notes
@views.route('view_notes/', methods=['GET', 'POST'])
@login_required
def view_notes():
    if request.method == 'POST':
        try:
            # Validate CSRF token
            csrf_token = request.form.get('csrf_token')
            validate_csrf(csrf_token)

            note = clean(request.form.get('note'))  # Sanitize input
            file_id = request.form.get('file_id')

            # Validate file ownership
            file = PcapLoc.query.get(file_id)
            if not file or file.user_id != current_user.id:
                flash('Unauthorized access to file!', category='error')
                logging.warning(f"Unauthorized access attempt to file {file_id} by user {current_user.id}")
                return redirect(url_for('views.home'))

            # Validate note content
            if len(note) < 1:

app/NetFlowInsight/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

        
        <title>{% block title %}Home{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbar"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" id="home" href="/">NetFlowInsight</a>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="notesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Notes
                    </a>
                    <div class="dropdown-menu bg-dark" aria-labelledby="notesDropdown">
                      <a class="dropdown-item text-white" href="/view_notes" id="view_notes">View Notes</a>
                    </div>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="analysisDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Analysis
                    </a>
                    <div class="dropdown-menu bg-dark" aria-labelledby="analysisDropdown">
                      <a class="dropdown-item text-white" href="/file_analysis_results" id="file_analysis">Analysis</a>
                    </div>
                  </li>
                  <a class="nav-item nav-link" id="logoutnav" href="/profile" style="margin-right: 100px;">Profile</a>
                  <a class="nav-item nav-link" id="logoutnav" href="/logout">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" id="home" href="#">NetFlowInsight</a>
                  <a class="nav-item nav-link" id="login" href="/login">Login</a>
                  <a class="nav-item nav-link" id="signup" href="/signup">Sign Up</a>
                {% endif %}
              </div>
            </div>
          </nav>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              <div class="container mt-3">
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }} custom-flash-message alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                {% endfor %}
              </div>
            {% endif %}
          {% endwith %}
          <div class="container-fluid">
            {% block content %} 
            <h1> Something's wrong! </h1>
            {%endblock%}
          </div>
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    </body>
</html>

app/NetFlowInsight/templates/file_analysis_results.html
{% extends "base.html" %}
{% block title %} Analysis Results {% endblock %}
{% block content %}
<div class="container mt-5">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Filename</th>
        <th>Date</th>
        <th>File</th>
        <th>Extension</th>
        <th>Result</th>
      </tr>
    </thead>
    <tbody>
      {% for file in user.pcap_loc %}
        {% for file_analysis in file.file_analysis %}
          {% if file_analysis.path.startswith("No") %}
          <tr>
            <td>{{ file.filename|escape }}</td>
            <td>{{ file.date.strftime("%Y-%m-%d  %H:%M") }}</td>
            <td colspan="3"> No Files Detected in the Pcap File! </td>
          </tr>
          {%else%}
          {% endif %}
          {% for file_result in file_analysis.file_result %}
      <tr>
        {% if loop.index == 1 %}
          <td rowspan="{{ file_analysis.file_result|length }}">{{ file.filename|escape }}</td>
          <td rowspan="{{ file_analysis.file_result|length }}">{{ file.date.strftime("%Y-%m-%d  %H:%M") }}</td>
        {% endif %}
          <td>
            <!-- Make the hash a clickable link for downloading -->
            <a href="{{ url_for('views.download_file', file_path=file_result.filepath|escape) }}" title="Click to download">
              {{ file_result.filename|escape }}
            </a>
          </td>
          <td>{{ file_result.extension_type|escape }}</td>
          <td>
            {{ file_result.result.replace('scores:', '<br>Scores:')
                                 .replace('metadefender:', '<br>Metadefender:')
                                 .replace('virustotal:', '<br>VirusTotal:')
                                 .replace('crowdstrike falcon static analysis (ml):', '<br>CrowdStrike Falcon Static Analysis (ML):')
                                 .replace('final verdict:', '<br>Final Verdict:')
                                 .replace('Groq Analysis:', '<br>Groq Analysis:<br>')
                                 .replace('Verdict:', '<br>Verdict:<br>')|safe }}
          </td>
      </tr>
      {% endfor %}
      {% endfor %}
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/NetFlowInsight/templates/home.html
{% extends "base.html" %}
{% block title %} NetFlowInsight {% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title mb-4">Upload PCAP File</h2>
      <form action="/upload" method="POST" enctype="multipart/form-data">
        <!-- CSRF token added here -->
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="form-group">
          <label for="pcap_file">Select PCAP File:</label>
          <input type="file" class="form-control-file" id="pcap_file" name="pcap_file" accept=".pcap,.pcapng">
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
      </form>
    </div>
  </div>
</div>

<hr>

<div class="container mt-5">
  <h1 class="text-center">Your Uploaded Files</h1>
  <ul class="list-group list-group-flush" id="filename">
    {% for file in user.pcap_loc %}
    <li class="list-group-item">
      <div class="d-flex justify-content-between align-items-center">
        <span class="filename">{{ file.filename }}</span>
        <span class="date">{{ file.date.strftime("%Y-%m-%d  %H:%M") }}</span>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

app/NetFlowInsight/templates/login.html
{% extends "base.html" %}
{% block title %} Analysis Results {% endblock %}
{% block content %}
<form method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <h3 align="center"> Login </h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" 
        {% if email %}
        value="{{ email|escape }}"
        {% else %}
        placeholder="Enter Email Address" 
        {% endif %}
        required/>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <div class="input-group">
            <input type="password" class="form-control" id="password" name="password"
            {% if request.form.password %}
                value="{{ request.form.password|escape }}"
            {% else %}
                placeholder="Enter Password" 
            {% endif %}
            required/>
            <label class="toggle-eye" for="password-toggle">
                <input type="checkbox" id="password-toggle" onclick="toggle_password_visibility('password')">
                <i class="fas fa-eye"></i>
            </label>
        </div>
    </div>
    <br>
    <h3 align="center"><button type="Submit" class="btn btn-primary">Login</button></h3>
</form>
{% endblock %}

app/NetFlowInsight/templates/make_notes.html
{% extends "base.html" %} 
{% block title %} Make Notes {% endblock %}
{% block content %}
  <div class="container mt-5">
    <h1 class="notes-heading">New Note</h1>
    <form method="POST">
      <!-- CSRF token added here -->
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <div class="form-group">
        <textarea name="note" id="note" class="form-control" placeholder="Write your note here"></textarea>
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary">Add Note</button>
      </div>
    </form>
  </div>
{% endblock %}

app/NetFlowInsight/templates/profile.html
{% extends "base.html" %}
{% block title %} Profile Page {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h2 class="text-center mb-0">Your Profile</h2>
        </div>
        <div class="card-body">
            <div class="profile-details">
                <div class="row mb-3">
                    <div class="col-md-4 font-weight-bold">First Name:</div>
                    <div class="col-md-8">{{ user.firstname|escape }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-4 font-weight-bold">Last Name:</div>
                    <div class="col-md-8">{{ user.lastname|escape }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-4 font-weight-bold">Email:</div>
                    <div class="col-md-8">{{ user.email|escape }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-4 font-weight-bold">Open API Key:</div>
                    <div class="col-md-8">
                      <span id="apiKeyDisplay" class="badge badge-secondary p-2">{{ user.api_key[:4] + "****" |escape }}</span>
                      <button type="button" class="btn btn-sm btn-outline-primary ml-2" onclick="editApiKey()">
                        <i class="fas fa-pencil-alt"></i> Edit
                      </button>
                    </div>
                  </div>
                  <div id="apiKeyEditField" style="display: none;">
                    <form method="POST">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                      <div class="form-group">
                        <label for="editApiKeyInput" class="font-weight-bold">Edit API Key:</label>
                        <input type="text" class="form-control" id="editApiKeyInput" name="api_key" placeholder="Enter new API key">
                      </div>
                      <button type="button" class="btn btn-sm btn-success" onclick="saveEditedApiKey()">Save</button>
                      <button type="button" class="btn btn-sm btn-secondary" onclick="cancelEditApiKey()">Cancel</button>
                    </form>
                  </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/NetFlowInsight/templates/signup.html
{% extends "base.html" %}
{% block title %} Signup {% endblock %}
{% block content %}
<form method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <h3 align="center"> Sign up </h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" 
        {% if request.form.email %}
            value="{{request.form.email}}"
        {% else %}
            placeholder="Enter Email Address" 
        {% endif %}
        required/>
    </div>
    <div class="form-group">
        <label for="firstname">First Name</label>
        <input type="text" class="form-control" id="firstname" name="firstname" 
        {% if request.form.firstname %}
            value="{{request.form.firstname}}"
        {% else %}
            placeholder="Enter First Name" 
        {% endif %}
        required/>
    </div>
    <div class="form-group">
        <label for="lastname">Last Name</label>
        <input type="text" class="form-control" id="lastname" name="lastname" 
        {% if request.form.lastname %}
            value="{{request.form.lastname}}"
        {% else %}
            placeholder="Enter Last Name" 
        {% endif %}
        required/>
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" required/>
    </div>
    <div class="form-group">
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2" required/>
    </div>
    <br>
    <h3 align="center"><button type="Submit" class="btn btn-primary">Submit</button></h3>
</form>
{% endblock %}

app/NetFlowInsight/templates/view_notes.html
{% extends "base.html" %}
{% block title %} Your Notes {% endblock %}
{% block content %}
<div class="container mt-5">
  <h1 class="text-center">Your File Analysis Results</h1>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Pcap File</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      {% for file in user.pcap_loc %}
        <tr>
          <td>{{ file.filename|escape }}</td>
          <td>
            <ul class="list-group list-group-flush" id="note">
              {% for note in file.note %}
              <li class="list-group-item" data-note-id="{{ note.id }}">
                <span class="note-display">{{ note.note|escape }}</span>
                <br>
                <span class="date">{{ note.date.strftime("%Y-%m-%d %H:%M") }}</span>
                <span aria-hidden="true" class="edit">
                  <button type="button" class="btn btn-sm btn-outline-primary" onclick="editNote('{{ note.id }}')">
                    <i class="fas fa-pencil-alt"></i>
                  </button>
                </span>
                <div class="note-edit-field" style="display: none;">
                  <input type="text" class="form-control edit-note-input">
                  <button type="button" class="btn btn-sm btn-outline-success mt-2" onclick="saveEditedNote('{{ note.id }}')">
                    Save
                  </button>
                </div>
                <button type="button" class="close" style="margin-right: 2%;" onClick="deleteNote('{{ note.id }}')">
                  <span aria-hidden="true">&times;</span>
                </button>
              </li>
              {% endfor %}
            </ul>
            <br>
            <br>
            <div class="container mt-5">
              <form method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="form-group">
                  <input type="hidden" name="file_id" value="{{ file.id }}">
                  <textarea name="note" id="note" class="form-control" placeholder="Add a new note"></textarea>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Add Note</button>
                </div>
              </form>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}